spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securelens_db
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9yU2VjdXJlTGVuc0RldmVsb3BtZW50T25seQ==}

securelens:
  api-keys:
    virustotal: ${VT_API_KEY:}
    abuseipdb: ${ABUSEIPDB_API_KEY:}
    shodan: ${SHODAN_API_KEY:}
    otx: ${OTX_API_KEY:}
